apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: leader-election-poc
  name: leader-election-poc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: leader-election-poc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: leader-election-poc
    spec:
      containers:
      - image: leader-election-poc:latest
        name: leader-election-container
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources: {}
status: {}
